In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('data/parsed.csv')
df.sample(5)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
2750,NaN,NaN,20270868,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20270868,",1.40,ml,...,reviewed,1538659147812,"M 1.4 - 41km NW of Willow, Alaska",0,earthquake,",geoserve,origin,phase-data,",-540.0,1539308353143,https://earthquake.usgs.gov/earthquakes/eventp...,Alaska
6154,NaN,2.0,73089931,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.13500,1.0,82.0,",nc73089931,nn00658221,",2.46,md,...,reviewed,1537951924840,"M 2.5 - 6km WNW of Bridgeport, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1538419514037,https://earthquake.usgs.gov/earthquakes/eventp...,California
3159,NaN,NaN,20270179,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20270179,",1.00,ml,...,reviewed,1538558821889,"M 1.0 - 11km NNW of Tanaina, Alaska",0,earthquake,",geoserve,origin,phase-data,",-540.0,1539219833568,https://earthquake.usgs.gov/earthquakes/eventp...,Alaska
5219,NaN,NaN,20273732,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20273732,",0.90,ml,...,reviewed,1538136389966,"M 0.9 - 67km WSW of Tok, Alaska",0,earthquake,",geoserve,origin,phase-data,",-540.0,1539039048393,https://earthquake.usgs.gov/earthquakes/eventp...,Alaska
6973,NaN,NaN,73089066,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01067,NaN,50.0,",nc73089066,",1.60,md,...,reviewed,1537796530050,"M 1.6 - 7km NW of The Geysers, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537862042303,https://earthquake.usgs.gov/earthquakes/eventp...,California

**Find the 95th percentile of earthquake magnitude in Japan using the mb
magnitude type.**

In [49]:
df[(df.parsed_place=='Japan')&(df.magType=='mb')].describe(percentiles=[0.95]).at['95%','mag']

4.9

In [52]:
#above method is too long.
#use the python code for percentiles which is quantile
df[(df.parsed_place=='Japan')&(df.magType=='mb')]['mag'].quantile(0.95)

4.9

**Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.**

In [82]:
all_earthquake = df[df.parsed_place=='Indonesia']['type'].count()
print(all_earthquake)
with_tsunami = df[(df.parsed_place=='Indonesia') & (df.tsunami==1)]['type'].count()
print(with_tsunami)
print(100*with_tsunami/all_earthquake,'%')

147
34
23.12925170068027 %

**Calculate summary statistics for earthquakes in Nevada.**

In [53]:
df[(df.parsed_place=='Nevada')].describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

**Add a column indicating whether the earthquake happened in a country or US
state that is on the Ring of Fire. Use Alaska, Antarctica (look for Antarctic), Bolivia,
California, Canada, Chile, Costa Rica, Ecuador, Fiji, Guatemala, Indonesia, Japan,
Kermadec Islands, Mexico (be careful not to select New Mexico), New Zealand,
Peru, Philippines, Russia, Taiwan, Tonga, and Washington.**

In [55]:
df['Ring of Fire'] = (
    (df.parsed_place=='Alaska')|(df.parsed_place=='Antarctic')|(df.parsed_place=='Bolivia')|(df.parsed_place=='California')|
    (df.parsed_place=='Canada')|(df.parsed_place=='Chile')|(df.parsed_place=='Costa Rica')|(df.parsed_place=='Ecuador')|
    (df.parsed_place=='Fiji')|(df.parsed_place=='Guatemala')|(df.parsed_place=='Indonesia')|(df.parsed_place=='Japan')|
    (df.parsed_place=='Kermadec Islands')|(df.parsed_place=='Mexico')|(df.parsed_place=='New Zealand')|
    (df.parsed_place=='Peru')|(df.parsed_place=='Philippines')|(df.parsed_place=='Russia')|(df.parsed_place=='Taiwan')|
    (df.parsed_place=='Tonga')|(df.parsed_place=='Washington')
)
df.head(10)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,parsed_place,Ring of Fire
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
5,NaN,NaN,2018286011,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.437300,NaN,158.0,",pr2018286011,",2.61,md,...,1539473686440,"M 2.6 - 55km ESE of Punta Cana, Dominican Repu...",0,earthquake,",geoserve,origin,phase-data,",-300.0,1539500579236,https://earthquake.usgs.gov/earthquakes/eventp...,Dominican Republic,False
6,NaN,NaN,20280432,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20280432,",1.70,ml,...,1539473176017,"M 1.7 - 105km W of Talkeetna, Alaska",0,earthquake,",geoserve,origin,",-540.0,1539473596465,https://earthquake.usgs.gov/earthquakes/eventp...,Alaska,True
7,NaN,NaN,73096936,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016220,NaN,83.0,",nc73096936,",1.13,md,...,1539473060280,"M 1.1 - 10km NW of Parkfield, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539476642808,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
8,NaN,NaN,73096931,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.009138,NaN,52.0,",nc73096931,",0.92,md,...,1539473042310,"M 0.9 - 6km NW of The Geysers, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539475027632,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
9,NaN,NaN,1000hbtn,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.191000,NaN,37.0,",us1000hbtn,",4.70,mb,...,1539472814760,"M 4.7 - 219km SSE of Saparua, Indonesia",0,earthquake,",geoserve,origin,phase-data,",540.0,1539473712040,https://earthquake.usgs.gov/earthquakes/eventp...,Indonesia,True

**Calculate the number of earthquakes in the Ring of Fire locations and the number
outside of them.**

In [72]:
in_location = df[df['Ring of Fire']==True]['type'].count()
print(in_location)
out_location = df[df['Ring of Fire']==False]['type'].count()
print(out_location)
#do the below simply since you know it contains only true and false
test = df['Ring of Fire'].value_counts()
print(test)

7184
2148
True     7184
False    2148
Name: Ring of Fire, dtype: int64

**Find the tsunami count along the Ring of Fire.**

In [57]:
tsunami_count = df[df['Ring of Fire']==True]['tsunami'].sum()
print(tsunami_count)

45

In [58]:
#OR
tsunami_count2 = df[(df['Ring of Fire']==True) & (df.tsunami==1)]['tsunami'].count()
print(tsunami_count2)

45

In [78]:
#best solution simple and short
df.loc[df['Ring of Fire'], 'tsunami'].sum()

45

In [ ]:
df['Ring of Fire'].value_counts

In [ ]:
df.['Ring of Fire'].value_counts

In [ ]:
df.['Ring of Fire']value_counts